services:
  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8000:8000"
    depends_on:
      - mongo
  
  task-service:
    build: ./task-service
    container_name: task-service
    ports:
      - "8001:8001"
    depends_on:
      - mongo
      - rabbitmq

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8002:8002"
    depends_on:
      - rabbitmq    
      - mongo


volumes:
  mongo_data: